# Generated by Django 3.2.12 on 2025-03-27 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('testcase_id', models.IntegerField()),
                ('description', models.TextField()),
                ('test_path', models.CharField(max_length=300)),
                ('screenshot', models.ImageField(upload_to='images/')),
                ('sevearity', models.CharField(max_length=300)),
                ('priority', models.CharField(max_length=300)),
                ('status', models.CharField(max_length=300)),
                ('date', models.DateField(auto_now=True)),
                ('tested_by_email', models.EmailField(max_length=254)),
                ('reproductionsteps', models.CharField(max_length=350)),
                ('environment', models.CharField(max_length=350)),
                ('browser', models.CharField(max_length=350)),
                ('os', models.CharField(max_length=350)),
                ('errordetails', models.CharField(max_length=350)),
                ('developer_email', models.CharField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='Testcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirements', models.CharField(max_length=350)),
                ('project_name', models.CharField(max_length=350)),
                ('module_name', models.CharField(max_length=350)),
                ('senario', models.CharField(max_length=350)),
                ('description', models.CharField(max_length=350)),
                ('input_data', models.CharField(max_length=350)),
                ('type_of_exception', models.CharField(max_length=350)),
                ('pre_condition', models.CharField(max_length=350)),
                ('expected_actual_result', models.CharField(max_length=350)),
                ('status', models.CharField(max_length=300)),
                ('date_of_creation', models.DateField(auto_now=True)),
                ('tester_email', models.EmailField(max_length=254)),
                ('teststeps', models.CharField(max_length=100)),
                ('priority', models.CharField(max_length=300)),
                ('comments', models.CharField(default='Empty', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=350)),
                ('priority', models.CharField(max_length=300)),
                ('ndatetime', models.DateTimeField(auto_now=True)),
                ('projects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminsapp.project')),
            ],
        ),
    ]
