# Generated by Django 3.2.12 on 2025-03-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_email', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('employee_email', models.EmailField(max_length=254)),
                ('project', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('enddate', models.DateField()),
            ],
        ),
    ]
